["```py\n# Chapter04/example1.py\n\nn_files = 10\nfiles = []\n\nfor i in range(n_files):\n    files.append(open('output1/sample%i.txt' % i, 'w'))\n```", "```py\n# Chapter4/example1.py\n\nn_files = 10000\nfiles = []\n\n# method 1\nfor i in range(n_files):\n    files.append(open('output1/sample%i.txt' % i, 'w'))\n```", "```py\n> python example1.py\nTraceback (most recent call last):\n File \"example1.py\", line 7, in <module>\nOSError: [Errno 24] Too many open files: 'output1/sample253.txt'\n```", "```py\n# Chapter04/example1.py\n\nn_files = 1000\nfiles = []\n\n# method 2\nfor i in range(n_files):\n    f = open('output1/sample%i.txt' % i, 'w')\n    files.append(f)\n    f.close()\n```", "```py\n# Chapter04/example1.py\n\nn_files = 254\nfiles = []\n\n# method 3\nfor i in range(n_files):\n    with open('output1/sample%i.txt' % i, 'w') as f:\n        files.append(f)\n```", "```py\nwith [expression] (as [target]):\n    [code]\n```", "```py\nwith [expression1] as [target1], [expression2] as [target2]:\n    [code]\n```", "```py\nwith [expression1] as [target1]:\n    with [expression2] as [target2]:\n        [code]\n```", "```py\n# Chapter04/example2.py\n\nfrom threading import Lock\n\nmy_lock = Lock()\n\ndef get_data_from_file_v1(filename):\n    my_lock.acquire()\n\n    with open(filename, 'r') as f:\n        data.append(f.read())\n\n    my_lock.release()\n\ndata = []\n\ntry:\n    get_data_from_file('output2/sample0.txt')\nexcept FileNotFoundError:\n    print('Encountered an exception...')\n\nmy_lock.acquire()\nprint('Lock can still be acquired.')\n```", "```py\n# Chapter04/example2.py\n\nfrom threading import Lock\n\nmy_lock = Lock()\n\ndef get_data_from_file_v2(filename):\n    with my_lock, open(filename, 'r') as f:\n        data.append(f.read())\n\ndata = []\n\ntry:\n    get_data_from_file_v2('output2/sample0.txt')\nexcept:\n    print('Encountered an exception...')\n\nmy_lock.acquire()\nprint('Lock acquired.')\n```", "```py\nwith my_lock:\n    with open(filename, 'r') as f:\n        data.append(f.read())\n```", "```py\n> python example2.py\nEncountered an exception...\nLock acquired.\n```"]